DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM cart_items;
DELETE FROM shopping_carts;
DELETE FROM books_categories;
DELETE FROM books;
DELETE FROM users_roles;
DELETE FROM users;
DELETE FROM categories;